### ISSUE TITLE
ValidationError: themeConfig.navbar.links has been renamed as themeConfig.navbar.items error

### ISSUE THREAD

**Issue by manjillama** [leapfrogtechnology/coding-guidelines#38]
Hi! I tried to run the project but it seems **a validation system was added recently to Docusaurus as an attempt to avoid user configuration errors.**

## Expected Behaviour
Project to sucessfully run without failure.

## Actual Behaviour 
Project fails to run with validation error.

``` 
ValidationError: themeConfig.navbar.links has been renamed as themeConfig.navbar.items
error 
```

I've applied a minor patch and sent a pull request fixing the issue.

## Step to reproduce
Clone the project and run ``` npm install ``` and then ``` yarn start ```

## Error Screenshot
![Screen Shot 2020-08-01 at 8 08 58 PM](https://user-images.githubusercontent.com/14996190/89104109-7be2b900-d436-11ea-940c-7053993c4f54.png)

P.S. I'm really sorry if you guys don't accept PR from outside the company. I saw an issue and decided to address it.

**Comment by mesaugat** [comment]
Hello @manjillama,

I believe you ran into the issue because you did `npm install` and it installed the latest docusaurus package.

We primarily use `yarn` and have `yarn.lock` included in the repository. Can you try using `yarn` to install the dependencies? I did this on my end and it's working fine.

Let me know if it doesn't work for you. Also, we do accept PRs from outside the company. 🙂

**Comment by manjillama** [comment]
@mesaugat Right! That fixed it! Thanks for the clarification. I'll go ahead and close the issue.
